import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { RefreshCw, ArrowUpRight } from "lucide-react";
import { Btn } from "./ui";
import { V5, V5_ATTESTATION_URL, V5_TRANSACTION_URL } from "@/lib/hackathon-v5";
import { readV5Evidence } from "@/lib/hackathon-v5.functions";

export type V5Result = Awaited<ReturnType<typeof readV5Evidence>>;
export function V5Proof({ initial }: { initial: V5Result }) {
  const [fresh, setFresh] = useState<V5Result | null>(null);
  const [busy, setBusy] = useState(false);
  const read = useServerFn(readV5Evidence);
  const result = fresh ?? initial;
  const data = result.ok ? result.data : null;
  const refresh = async () => { setBusy(true); try { setFresh(await read()); } catch { setFresh({ ok: false, error: "UNAVAILABLE — Devnet read failed. No transaction was executed." }); } finally { setBusy(false); } };
  return <>
    <section className="border-t py-9">
      <div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl text-gold">SOLANA DEVNET PROOF</h2><Btn onClick={() => { void refresh(); }} disabled={busy} className="min-h-11 shadow-none"><RefreshCw size={15} />{busy ? "Reading…" : "Read proof again"}</Btn></div>
      {!result.ok && <p role="alert" className="mt-5 text-sm text-warning">{result.error}</p>}
      <dl className="mt-6 grid min-w-0 gap-x-8 gap-y-5 sm:grid-cols-2">
        {[["Network", "Solana Devnet"], ["Transaction status", data?.transactionStatus ?? "UNVERIFIED"], ["CX7 Authority", V5.authority], ["Credential", V5.credential], ["Schema", V5.schema], ["Read at", data?.readAt ?? "Unavailable"]].map(([label, value]) => <div className="min-w-0" key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-all font-mono text-xs leading-6">{value}</dd></div>)}
      </dl>
      <div className="mt-6 space-y-5">
        {[["Transaction", V5.transaction, V5_TRANSACTION_URL], ["Attestation", V5.attestation, V5_ATTESTATION_URL]].map(([label, value, url]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><a href={url} target="_blank" rel="noopener noreferrer" className="mt-1 flex min-h-11 items-start gap-2 text-gold hover:underline"><span className="min-w-0 break-all font-mono text-xs leading-6">{value}</span><ArrowUpRight className="mt-1 shrink-0" size={16} /></a></div>)}
      </div>
    </section>
    <section className="border-t py-9">
      <h2 className="text-xl text-gold">WHAT WAS VERIFIED</h2>
      <p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">Evidence associated with a CX7 Decision Passport was issued to Solana Devnet. Its evidence hash is read back from the network and compared with the hash generated by CX7.</p>
      <dl className="mt-6 space-y-5">
        <div><dt className="text-xs text-muted-foreground">CX7 hash</dt><dd className="mt-2 break-all font-mono text-sm leading-7">{V5.hash}</dd></div>
        <div><dt className="text-xs text-muted-foreground">Read-back hash</dt><dd className="mt-2 break-all font-mono text-sm leading-7">{data?.hash ?? "UNAVAILABLE"}</dd></div>
      </dl>
      <div role="status" className="mt-6 flex flex-wrap items-center gap-3 border-l-2 border-success pl-4"><span className="text-xs text-muted-foreground">Read-back result</span><strong className={data?.match ? "font-mono text-xl text-success" : "font-mono text-xl text-warning"}>{data ? (data.match ? "MATCH" : "MISMATCH") : "UNVERIFIED"}</strong></div>
      <p className="mt-4 text-xs leading-6 text-muted-foreground">Recorded Passport status: {data?.snapshotStatus ?? "UNVERIFIED"}. Time check: {data?.timeStatus ?? "UNVERIFIED"}. These reads establish evidence integrity, not current enterprise authorization.</p>
    </section>
  </>;
}